# Generated by Django 6.0.2 on 2026-02-23 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Team Name')),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City / Club')),
                ('division', models.CharField(choices=[('pro_men', "Pro Men's"), ('pro_women', "Pro Women's"), ('amateur', 'Amateur / Mixed')], default='pro_men', max_length=50)),
                ('group_name', models.CharField(blank=True, max_length=10, null=True)),
                ('cap_name', models.CharField(max_length=50, verbose_name='Captain Name')),
                ('cap_surname', models.CharField(max_length=50, verbose_name='Captain Surname')),
                ('cap_email', models.EmailField(max_length=100, unique=True)),
                ('cap_phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('payment_status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Accepted'), (2, 'Refund')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.team')),
            ],
            options={
                'db_table': 'Players',
            },
        ),
    ]
