# Generated by Django 6.0.2 on 2026-02-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='division',
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='cap_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Captain Date of Birth'),
        ),
        migrations.AddField(
            model_name='team',
            name='cap_jersey',
            field=models.IntegerField(blank=True, null=True, verbose_name='Captain Jersey Number'),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='league_level',
            field=models.CharField(choices=[('1st', '1st Liga'), ('2nd', '2nd Liga'), ('3rd', '3rd Liga'), ('independent', 'Independent Team')], default='independent', max_length=50),
        ),
    ]
