# Generated by Django 6.0.2 on 2026-03-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_team_division_player_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='blik_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Assigned BLIK'),
        ),
    ]
