name: Deploy to Server

on:
  push:
    branches: ["court-tour"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted # <--- Это заставит задачу выполняться прямо в твоем LXC
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy locally
        run: |
          set -e
          echo "DEPLOY_SCRIPT_V_LOCAL"
          PROJECT_DIR="/srv/vol-registr"
          
          cd "$PROJECT_DIR"
          git fetch --prune origin court-tour
          git reset --hard origin/court-tour
          
          ASSET_VERSION=$(git rev-parse --short HEAD)
          
          # Даем права на скрипты
          chmod +x scripts/*.sh
          
          # Запускаем деплой (venv, миграции и т.д.)
          VENV_DIR=".venv" \
          PYTHON_BIN="python3" \
          STATIC_ASSET_VERSION="$ASSET_VERSION" \
          sh scripts/deploy-app.sh
          
          # Перезапуск Gunicorn (порт 8001 - твой DEV)
          PIDFILE="gunicorn.pid" PORT="8001" sh scripts/stop-server.sh || true
          
          APP_MODULE="vol_registr.wsgi:application" \
          BIND_ADDR="0.0.0.0:8001" \
          WORKERS="3" \
          PIDFILE="gunicorn.pid" \
          LOGFILE="gunicorn.log" \
          VENV_GUNICORN=".venv/bin/gunicorn" \
          sh scripts/start-server.sh
